variables:
  remote_host: remote-host-ip

jobs:
  json_benchmarks:
    sources:
      JsonNetWithNugetBenchmark:
        localFolder: .
    project: JsonNetWithNugetBenchmark/JsonNetWithNugetBenchmark.csproj
    variables:
      filterArg: "JsonNetWithNugetBenchmark.JsonNetSerializerBenchmark.*"
    arguments: --filter {{filterArg}}
    options:
      benchmarkDotNet: true

scenarios:
  demo_benchmark:
    application:
      job: json_benchmarks

profiles:
  local:
    jobs:
      application:
        endpoints:
          - http://localhost:5010
        framework: net9.0
        sdkVersion: 9.0.200
        runtimeVersion: 9.0.2
        aspNetCoreVersion: 9.0.2

  remote:
    jobs: 
      application:
        endpoints: 
          - "http://{{remote_host}}:5010"
        framework: net9.0
        sdkVersion: 9.0.200
        runtimeVersion: 9.0.2
        aspNetCoreVersion: 9.0.2